"""Add capabilities and typed activation for AI models

Revision ID: 26f5f8f6bde8
Revises: bb2f623f4acb
Create Date: 2025-07-30 00:30:08.658263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f5f8f6bde8'
down_revision: Union[str, Sequence[str], None] = 'bb2f623f4acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('capabilities', sa.Text(), nullable=False, server_default='[]'))
    op.add_column('ai_models', sa.Column('is_active_general', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('ai_models', sa.Column('is_active_vision', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('ai_models', sa.Column('is_active_fast', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('ai_models', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('ai_models', 'is_active_fast')
    op.drop_column('ai_models', 'is_active_vision')
    op.drop_column('ai_models', 'is_active_general')
    op.drop_column('ai_models', 'capabilities')
    # ### end Alembic commands ###
