"""Introduce defendants table for multi-defendant support

Revision ID: 2dd1c5baaa07
Revises: da5b02bdf524
Create Date: 2025-07-30 16:48:26.239883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd1c5baaa07'
down_revision: Union[str, Sequence[str], None] = 'da5b02bdf524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('defendants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False, comment='被告姓名或名称'),
        sa.Column('verification_code', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('verification_code')
    )

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_defendant_id', sa.Integer(), nullable=True))
        # 在批处理模式下创建外键
        batch_op.create_foreign_key(
            'fk_documents_author_defendant_id_defendants', # 给约束一个明确的名字
            'defendants', 
            ['author_defendant_id'], 
            ['id']
        )
    
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('defendant_code')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defendant_code', sa.VARCHAR(), nullable=False, server_default=sa.text("'default_code'")))
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_author_defendant_id_defendants', type_='foreignkey')
        batch_op.drop_column('author_defendant_id')
    op.drop_table('defendants')
    # ### end Alembic commands ###
