"""Initial schema based on final models without pgvector

Revision ID: 5fb77b5bcc1a
Revises: 
Create Date: 2025-08-14 12:49:51.564294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb77b5bcc1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False, comment='例如: deepseek-chat'),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False, comment="模型能力, JSON数组: ['general', 'vision', 'fast']"),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度 (0-2)'),
    sa.Column('top_p', sa.Float(), nullable=True, comment='Top-P (0-1)'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='Max Tokens'),
    sa.Column('is_active_general', sa.Boolean(), nullable=False),
    sa.Column('is_active_vision', sa.Boolean(), nullable=False),
    sa.Column('is_active_fast', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('case_cause', sa.String(), nullable=False),
    sa.Column('plaintiff_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_cause'), 'cases', ['case_cause'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('rag_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_endpoint', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('output_dim', sa.Integer(), nullable=True, comment='仅 Embedding 模型需要, 输出向量维度'),
    sa.Column('similarity_top_k', sa.Integer(), nullable=True, comment='仅 Embedding 模型需要, 初步检索数量'),
    sa.Column('rerank_top_k', sa.Integer(), nullable=True, comment='仅 Rerank 模型需要, 最终返回数量'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vector_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_cause', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_stores_case_cause'), 'vector_stores', ['case_cause'], unique=True)
    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('request_source', sa.String(), nullable=True, comment="API call source, e.g., 'chat'"),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='被告姓名或名称'),
    sa.Column('verification_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('document_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='文档组名称'),
    sa.Column('embedding_model_name', sa.String(), nullable=True),
    sa.Column('source_filenames', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['vector_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_defendant_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('form_data', sa.Text(), nullable=False),
    sa.Column('final_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_defendant_id'], ['defendants.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'document_type', 'version', 'author_defendant_id', name='_case_doc_version_uc')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('document_groups')
    op.drop_table('defendants')
    op.drop_table('ai_usage_log')
    op.drop_index(op.f('ix_vector_stores_case_cause'), table_name='vector_stores')
    op.drop_table('vector_stores')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('rag_models')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_cause'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
