"""Update unique constraint on documents table

Revision ID: 62da617e32c9
Revises: 2dd1c5baaa07
Create Date: 2025-08-01 00:41:00.468021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '62da617e32c9'
down_revision: Union[str, Sequence[str], None] = '2dd1c5baaa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        # 先删除旧的约束（如果存在且名字已知）
        try:
            batch_op.drop_constraint('_case_doc_version_uc', type_='unique')
        except Exception:
            # 如果旧约束不存在或名字不同，可能会报错，忽略它
            pass
        # 创建新的、包含 author_defendant_id 的约束
        batch_op.create_unique_constraint(
            '_case_doc_version_uc', 
            ['case_id', 'document_type', 'version', 'author_defendant_id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_case_doc_version_uc', 'documents', type_='unique')
    op.create_unique_constraint(op.f('_case_doc_version_uc'), 'documents', ['case_id', 'document_type', 'version'])
    # ### end Alembic commands ###
