"""Add parameters to AIModel table

Revision ID: 7b8c91a630a2
Revises: 62da617e32c9
Create Date: 2025-08-01 22:49:32.710800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8c91a630a2'
down_revision: Union[str, Sequence[str], None] = '62da617e32c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('temperature', sa.Float(), nullable=True, comment='温度 (0-2)'))
    op.add_column('ai_models', sa.Column('top_p', sa.Float(), nullable=True, comment='Top-P (0-1)'))
    op.add_column('ai_models', sa.Column('max_tokens', sa.Integer(), nullable=True, comment='Max Tokens'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'max_tokens')
    op.drop_column('ai_models', 'top_p')
    op.drop_column('ai_models', 'temperature')
    # ### end Alembic commands ###
