from typing import Dict, Any, List

TEMPLATE_DATABASE: Dict[str, Any] = {
    "claim": {
        "civil": [
            {"id": "divorce", "name": "离婚纠纷", "path": "/claim/divorce",
                "description": "适用于婚姻关系破裂，一方或双方提起离婚诉讼。", "disabled": False},
            {"id": "sales-contract", "name": "买卖合同纠纷", "path": "/claim/sales-contract",
                "description": "适用于因商品或货物买卖合同的履行、违约等引起的纠纷。", "disabled": False},
            {"id": "housing-sales-contract", "name": "房屋买卖合同纠纷", "path": "/claim/housing-sales-contract",
                "description": "适用于因房屋买卖合同的签订、履行、解除等引起的纠纷。", "disabled": False},
            {"id": "financial-loan-contract", "name": "金融借款合同纠纷", "path": "/claim/financial-loan-contract",
                "description": "适用于银行或其他金融机构与借款人之间因借款合同产生的纠纷。", "disabled": False},
            {"id": "private-lending", "name": "民间借贷纠纷", "path": "/claim/private-lending",
                "description": "适用于自然人、法人、其他组织之间及其相互之间进行资金融通的行为产生的纠纷。", "disabled": False},
            {"id": "credit-card", "name": "信用卡纠纷", "path": "/claim/credit-card",
                "description": "适用于因信用卡申领、使用、还款等环节产生的纠纷。", "disabled": False},
            {"id": "housing-lease", "name": "房屋租赁合同纠纷", "path": "/claim/housing-lease",
                "description": "适用于因租赁房屋产生的各类合同纠纷。", "disabled": False},
            {"id": "financial-leasing-contract", "name": "融资租赁合同纠纷", "path": "/claim/financial-leasing-contract",
                "description": "适用于因融资租赁合同的履行、违约等问题产生的纠纷。", "disabled": True},
            {"id": "construction-contract", "name": "建设工程施工合同纠纷", "path": "/claim/construction-contract",
                "description": "适用于在建设工程施工合同履行过程中产生的各类纠纷。", "disabled": False},
            {"id": "property-management-contract", "name": "物业服务合同纠纷", "path": "/claim/property-management-contract",
                "description": "适用于业主与物业公司之间因物业服务合同产生的纠纷。", "disabled": False},
            {"id": "labor-dispute", "name": "劳动争议纠纷", "path": "/claim/labor-dispute",
                "description": "适用于劳动者与用人单位之间因劳动关系产生的争议。", "disabled": False},
            {"id": "securities-misrepresentation", "name": "证券虚假陈述责任纠纷", "path": "/claim/securities-misrepresentation",
                "description": "适用于因上市公司等信息披露义务人虚假陈述导致投资者损失的纠纷。", "disabled": True},
            {"id": "property-damage-insurance", "name": "财产损失保险合同纠纷", "path": "/claim/property-damage-insurance",
                "description": "适用于投保人与保险公司之间因财产损失保险合同产生的理赔等纠纷。", "disabled": True},
            {"id": "liability-insurance", "name": "责任保险合同纠纷", "path": "/claim/liability-insurance",
                "description": "适用于因责任保险合同的理赔、免责条款等产生的纠纷。", "disabled": True},
            {"id": "guarantee-insurance", "name": "保证保险合同纠纷", "path": "/claim/guarantee-insurance",
                "description": "适用于因保证保险合同（如贷款保证保险）产生的纠纷。", "disabled": True},
            {"id": "personal-insurance", "name": "人身保险合同纠纷", "path": "/claim/personal-insurance",
                "description": "适用于因人寿保险、健康保险、意外伤害保险等合同产生的纠纷。", "disabled": True},
            {"id": "traffic-accident", "name": "机动车交通事故责任纠纷", "path": "/claim/traffic-accident",
                "description": "适用于因机动车交通事故造成人身伤害或财产损失的侵权责任纠纷。", "disabled": False},
            {"id": "copyright-infringement", "name": "侵害著作权及邻接权纠纷", "path": "/claim/copyright-infringement",
                "description": "适用于因他人未经许可使用作品等行为提起的著作权侵权诉讼。", "disabled": True},
            {"id": "trademark-infringement", "name": "侵害商标权纠纷", "path": "/claim/trademark-infringement",
                "description": "适用于因他人假冒、仿冒注册商标等行为提起的商标侵权诉讼。", "disabled": True},
            {"id": "invention-patent-infringement", "name": "侵害发明专利权纠纷", "path": "/claim/invention-patent-infringement",
                "description": "适用于因他人未经许可实施发明专利提起的侵权诉讼。", "disabled": True},
            {"id": "design-patent-infringement", "name": "侵害外观设计专利权纠纷", "path": "/claim/design-patent-infringement",
                "description": "适用于因他人未经许可制造、销售外观设计专利产品提起的侵权诉讼。", "disabled": True},
            {"id": "plant-variety-rights-infringement", "name": "侵害植物新品种权纠纷", "path": "/claim/plant-variety-rights-infringement",
                "description": "适用于因他人未经授权繁殖、销售受保护的植物新品种提起的侵权诉讼。", "disabled": True},
            {"id": "trade-secret-infringement", "name": "侵害商业秘密纠纷", "path": "/claim/trade-secret-infringement",
                "description": "适用于因他人窃取、披露、使用商业秘密提起的侵权诉讼。", "disabled": True},
            {"id": "technology-contract", "name": "技术合同纠纷", "path": "/claim/technology-contract",
                "description": "适用于因技术开发、转让、咨询、服务等合同产生的纠纷。", "disabled": True},
            {"id": "unfair-competition", "name": "不正当竞争纠纷", "path": "/claim/unfair-competition",
                "description": "适用于因仿冒、虚假宣传、商业诋毁等不正当竞争行为引起的纠纷。", "disabled": False},
            {"id": "monopoly-dispute", "name": "垄断纠纷", "path": "/claim/monopoly-dispute",
                "description": "适用于因垄断协议、滥用市场支配地位等垄断行为引起的民事诉讼。", "disabled": True},
            {"id": "ship-collision-damage", "name": "船舶碰撞损害责任纠纷", "path": "/claim/ship-collision-damage",
                "description": "适用于因船舶在海上或通航水域发生碰撞造成损失提起的诉讼。", "disabled": True},
            {"id": "maritime-personal-injury", "name": "海上、通海水域人身损害责任纠纷", "path": "/claim/maritime-personal-injury",
                "description": "适用于在海上或与海相通的可航水域作业、航行时发生的人身损害赔偿纠纷。", "disabled": True},
            {"id": "maritime-freight-forwarding", "name": "海上、通海水域货运代理合同纠纷", "path": "/claim/maritime-freight-forwarding",
                "description": "适用于因海上或通海水域的货物运输代理合同产生的纠纷。", "disabled": True},
            {"id": "seafarer-labor-contract", "name": "船员劳务合同纠纷", "path": "/claim/seafarer-labor-contract",
                "description": "适用于船员与船舶所有人或经营人之间因劳务合同产生的纠纷。", "disabled": True},
            {"id": "environmental-pollution-public-interest", "name": "环境污染民事公益诉讼", "path": "/claim/environmental-pollution-public-interest",
                "description": "适用于法律规定的机关和组织就污染环境、破坏生态的行为提起的民事公益诉讼。", "disabled": True},
            {"id": "ecological-damage-public-interest", "name": "生态破坏民事公益诉讼", "path": "/claim/ecological-damage-public-interest",
                "description": "适用于法律规定的机关和组织就破坏生态的行为提起的民事公益诉讼。", "disabled": True},
            {"id": "environmental-damage-compensation", "name": "生态环境损害赔偿诉讼", "path": "/claim/environmental-damage-compensation",
                "description": "适用于省级、市地级政府及其指定部门就生态环境损害提起的赔偿诉讼。", "disabled": True}
        ],
        "criminal": [
            {"id": "insult", "name": "侮辱案(附带民事)", "path": "/claim/insult",
             "description": "适用于公民个人就公然侮辱他人、情节严重的行为提起的刑事自诉。", "disabled": True},
            {"id": "defamation", "name": "诽谤案(附带民事)", "path": "/claim/defamation",
             "description": "适用于公民个人就捏造事实诽谤他人、情节严重的行为提起的刑事自诉。", "disabled": True},
            {"id": "bigamy", "name": "重婚案(附带民事)", "path": "/claim/bigamy",
             "description": "适用于被害人就有配偶而重婚的或明知他人有配偶而与之结婚的行为提起的刑事自诉。", "disabled": True},
            {"id": "refusal-to-execute-judgment", "name": "拒不执行判决、裁定案(附带民事)", "path": "/claim/refusal-to-execute-judgment",
             "description": "适用于申请执行人就有能力执行而拒不执行判决、裁定的行为提起的刑事自诉。", "disabled": True}
        ],
        "administrative": [
            {"id": "trademark-rejection-review", "name": "商标申请驳回复审纠纷", "path": "/claim/trademark-rejection-review",
                "description": "适用于不服商标评审委员会的驳回申请复审决定而向法院提起的行政诉讼。", "disabled": True},
            {"id": "trademark-cancellation-review", "name": "商标撤销复审纠纷", "path": "/claim/trademark-cancellation-review",
                "description": "适用于不服商标评审委员会的撤销注册商标复审决定而提起的行政诉讼。", "disabled": True},
            {"id": "trademark-invalidation", "name": "商标无效行政纠纷", "path": "/claim/trademark-invalidation",
                "description": "适用于不服商标评审委员会宣告注册商标无效的裁定而提起的行政诉讼。", "disabled": True},
            {"id": "patent-rejection-review", "name": "专利申请驳回复审纠纷", "path": "/claim/patent-rejection-review",
                "description": "适用于不服专利复审委员会的驳回申请复审决定而提起的行政诉讼。", "disabled": True},
            {"id": "patent-invalidation", "name": "专利无效行政纠纷", "path": "/claim/patent-invalidation",
                "description": "适用于不服专利复审委员会的宣告专利权无效决定而提起的行政诉讼。", "disabled": True},
            {"id": "monopoly-dispute-admin", "name": "垄断纠纷(行政)", "path": "/claim/monopoly-dispute-admin",
             "description": "适用于不服反垄断执法机构的行政处罚决定等具体行政行为而提起的行政诉讼。", "disabled": True},
            {"id": "administrative-penalty", "name": "行政处罚", "path": "/claim/administrative-penalty",
                "description": "适用于公民、法人或其他组织认为行政机关的行政处罚决定侵犯其合法权益提起的诉讼。", "disabled": True},
            {"id": "administrative-compulsory-enforcement", "name": "行政强制执行",
                "path": "/claim/administrative-compulsory-enforcement", "description": "适用于对行政机关的强制执行措施或决定不服提起的诉讼。", "disabled": True},
            {"id": "administrative-license", "name": "行政许可", "path": "/claim/administrative-license",
                "description": "适用于对行政机关作出的有关行政许可的决定不服提起的诉讼。", "disabled": True},
            {"id": "land-expropriation", "name": "国有土地上房屋征收决定", "path": "/claim/land-expropriation",
                "description": "适用于对市、县级人民政府作出的房屋征收决定不服提起的诉讼。", "disabled": True},
            {"id": "work-injury-insurance-determination", "name": "工伤保险资格或者待遇认定", "path": "/claim/work-injury-insurance-determination",
                "description": "适用于对社会保险行政部门作出的工伤认定、待遇核定等决定不服提起的诉讼。", "disabled": True},
            {"id": "government-information-disclosure", "name": "政府信息公开", "path": "/claim/government-information-disclosure",
                "description": "适用于因向行政机关申请获取政府信息被拒绝或未获答复而提起的诉讼。", "disabled": True},
            {"id": "administrative-reconsideration", "name": "行政复议", "path": "/claim/administrative-reconsideration",
                "description": "适用于对行政复议机关作出的复议决定不服，或者复议机关逾期不作决定而提起的诉讼。", "disabled": True},
            {"id": "administrative-agreement", "name": "行政协议", "path": "/claim/administrative-agreement",
                "description": "适用于因行政机关不依法履行、未按照约定履行行政协议等行为提起的诉讼。", "disabled": True},
            {"id": "administrative-compensation", "name": "行政补偿", "path": "/claim/administrative-compensation",
                "description": "适用于因合法行政行为造成损失，请求行政机关予以补偿的诉讼。", "disabled": True},
            {"id": "administrative-reparation", "name": "行政赔偿", "path": "/claim/administrative-reparation",
                "description": "适用于因行政机关及其工作人员的违法职务行为造成损害，请求国家赔偿的诉讼。", "disabled": True},
            {"id": "failure-to-perform-statutory-duties", "name": "不履行法定职责", "path": "/claim/failure-to-perform-statutory-duties",
                "description": "适用于申请行政机关履行保护人身权、财产权等法定职责，行政机关拒绝履行或不予答复而提起的诉讼。", "disabled": True}
        ]
    },
    "defense": {
        "civil": [
            {"id": "divorce", "name": "离婚纠纷", "path": "/defense/divorce",
                "description": "针对离婚诉讼提出的答辩，表明是否同意离婚、财产分割及子女抚养意见。", "disabled": False},
            {"id": "sales-contract", "name": "买卖合同纠纷", "path": "/defense/sales-contract",
             "description": "针对买卖合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "housing-sales-contract", "name": "房屋买卖合同纠纷", "path": "/defense/housing-sales-contract",
             "description": "针对房屋买卖合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "financial-loan-contract", "name": "金融借款合同纠纷", "path": "/defense/financial-loan-contract",
             "description": "针对金融借款合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "private-lending", "name": "民间借贷纠纷", "path": "/defense/private-lending",
             "description": "针对民间借贷纠纷起诉提出的答辩。", "disabled": False},
            {"id": "credit-card", "name": "信用卡纠纷", "path": "/defense/credit-card",
             "description": "针对信用卡纠纷起诉提出的答辩。", "disabled": False},
            {"id": "housing-lease", "name": "房屋租赁合同纠纷", "path": "/defense/housing-lease",
             "description": "针对房屋租赁纠纷起诉提出的答辩。", "disabled": False},
            {"id": "financial-leasing-contract", "name": "融资租赁合同纠纷", "path": "/defense/financial-leasing-contract",
             "description": "针对融资租赁合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "construction-contract", "name": "建设工程施工合同纠纷", "path": "/defense/construction-contract",
             "description": "针对建设工程施工合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "property-management-contract", "name": "物业服务合同纠纷",
             "path": "/defense/property-management-contract", "description": "针对物业服务合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "labor-dispute", "name": "劳动争议纠纷", "path": "/defense/labor-dispute",
             "description": "针对劳动争议纠纷起诉提出的答辩。", "disabled": False},
            {"id": "securities-misrepresentation", "name": "证券虚假陈述责任纠纷",
             "path": "/defense/securities-misrepresentation", "description": "针对证券虚假陈述责任纠纷起诉提出的答辩。", "disabled": False},
            {"id": "property-damage-insurance", "name": "财产损失保险合同纠纷", "path": "/defense/property-damage-insurance",
             "description": "针对财产损失保险合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "liability-insurance", "name": "责任保险合同纠纷", "path": "/defense/liability-insurance",
             "description": "针对责任保险合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "guarantee-insurance", "name": "保证保险合同纠纷", "path": "/defense/guarantee-insurance",
             "description": "针对保证保险合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "personal-insurance", "name": "人身保险合同纠纷", "path": "/defense/personal-insurance",
             "description": "针对人身保险合同纠纷起诉提出的答辩。", "disabled": False},
            {"id": "traffic-accident", "name": "机动车交通事故责任纠纷", "path": "/defense/traffic-accident",
             "description": "针对机动车交通事故责任纠纷起诉提出的答辩。", "disabled": False},
            {"id": "copyright-infringement", "name": "侵害著作权及邻接权纠纷", "path": "/defense/copyright-infringement",
             "description": "针对侵害著作权及邻接权纠纷起诉提出的答辩。", "disabled": False},
            {"id": "trademark-infringement", "name": "侵害商标权纠纷", "path": "/defense/trademark-infringement",
             "description": "针对侵害商标权纠纷起诉提出的答辩。", "disabled": True},
            {"id": "invention-patent-infringement", "name": "侵害发明专利权纠纷",
             "path": "/defense/invention-patent-infringement", "description": "针对侵害发明专利权纠纷起诉提出的答辩。", "disabled": True},
            {"id": "design-patent-infringement", "name": "侵害外观设计专利权纠纷", "path": "/defense/design-patent-infringement",
             "description": "针对侵害外观设计专利权纠纷起诉提出的答辩。", "disabled": True},
            {"id": "plant-variety-rights-infringement", "name": "侵害植物新品种权纠纷",
             "path": "/defense/plant-variety-rights-infringement", "description": "针对侵害植物新品种权纠纷起诉提出的答辩。", "disabled": True},
            {"id": "trade-secret-infringement", "name": "侵害商业秘密纠纷", "path": "/defense/trade-secret-infringement",
             "description": "针对侵害商业秘密纠纷起诉提出的答辩。", "disabled": True},
            {"id": "technology-contract", "name": "技术合同纠纷", "path": "/defense/technology-contract",
             "description": "针对技术合同纠纷起诉提出的答辩。", "disabled": True},
            {"id": "unfair-competition", "name": "不正当竞争纠纷", "path": "/defense/unfair-competition",
             "description": "针对不正当竞争纠纷起诉提出的答辩。", "disabled": False},
            {"id": "monopoly-dispute", "name": "垄断纠纷", "path": "/defense/monopoly-dispute",
             "description": "针对垄断纠纷起诉提出的答辩。", "disabled": True},
            {"id": "ship-collision-damage", "name": "船舶碰撞损害责任纠纷", "path": "/defense/ship-collision-damage",
             "description": "针对船舶碰撞损害责任纠纷起诉提出的答辩。", "disabled": True},
            {"id": "maritime-personal-injury", "name": "海上、通海水域人身损害责任纠纷", "path": "/defense/maritime-personal-injury",
             "description": "针对海上、通海水域人身损害责任纠纷起诉提出的答辩。", "disabled": True},
            {"id": "maritime-freight-forwarding", "name": "海上、通海水域货运代理合同纠纷",
             "path": "/defense/maritime-freight-forwarding", "description": "针对海上、通海水域货运代理合同纠纷起诉提出的答辩。", "disabled": True},
            {"id": "seafarer-labor-contract", "name": "船员劳务合同纠纷", "path": "/defense/seafarer-labor-contract",
             "description": "针对船员劳务合同纠纷起诉提出的答辩。", "disabled": True},
            {"id": "environmental-pollution-public-interest", "name": "环境污染民事公益诉讼",
             "path": "/defense/environmental-pollution-public-interest", "description": "针对环境污染民事公益诉讼起诉提出的答辩。", "disabled": False},
            {"id": "ecological-damage-public-interest", "name": "生态破坏民事公益诉讼",
             "path": "/defense/ecological-damage-public-interest", "description": "针对生态破坏民事公益诉讼起诉提出的答辩。", "disabled": False},
            {"id": "environmental-damage-compensation", "name": "生态环境损害赔偿诉讼",
             "path": "/defense/environmental-damage-compensation", "description": "针对生态环境损害赔偿诉讼起诉提出的答辩。", "disabled": False}

        ],
        "criminal": [
            {"id": "insult", "name": "侮辱案(附带民事)", "path": "/defense/insult",
             "description": "针对侮辱案刑事自诉提出的答辩。", "disabled": True},
            {"id": "defamation", "name": "诽谤案(附带民事)", "path": "/defense/defamation",
             "description": "针对诽谤案刑事自诉提出的答辩。", "disabled": True},
            {"id": "bigamy", "name": "重婚案(附带民事)", "path": "/defense/bigamy",
             "description": "针对重婚案刑事自诉提出的答辩。", "disabled": True},
            {"id": "refusal-to-execute-judgment",
             "name": "拒不执行判决、裁定案(附带民事)", "path": "/defense/refusal-to-execute-judgment", "description": "针对拒不执行判决、裁定案刑事自诉提出的答辩。", "disabled": True},

        ],
        "administrative": [
            {"id": "generic-admin-defense", "name": "行政答辩状(通用)", "path": "/defense/generic-admin-defense",
             "description": "适用于行政机关作为被告时，针对行政起诉状提出的通用答辩。", "disabled": True},
            {"id": "trademark-rejection-review", "name": "商标申请驳回复审纠纷", "path": "/defense/trademark-rejection-review",
             "description": "被告行政机关针对商标申请驳回复审诉讼提出的答辩。", "disabled": True},
            {"id": "trademark-cancellation-review-third-party", "name": "商标撤销复审纠纷第三人意见陈述书",
             "path": "/defense/trademark-cancellation-review-third-party", "description": "作为第三人参与商标撤销复审行政诉讼时，向法院陈述意见。", "disabled": True},
            {"id": "trademark-invalidation-third-party", "name": "商标无效行政纠纷第三人意见陈述书",
             "path": "/defense/trademark-invalidation-third-party", "description": "作为第三人参与商标无效行政诉讼时，向法院陈述意见。", "disabled": True},
            {"id": "patent-invalidation-third-party", "name": "专利无效行政纠纷第三人意见陈述书",
             "path": "/defense/patent-invalidation-third-party", "description": "作为第三人参与专利无效行政诉讼时，向法院陈述意见。", "disabled": True},
            {"id": "wrongful-enforcement-compensation", "name": "错误执行国家赔偿",
             "path": "/defense/wrongful-enforcement-compensation", "description": "赔偿义务机关针对错误执行赔偿申请提出的答辩。", "disabled": True},
            {"id": "unlawful-detention-compensation", "name": "违法刑事拘留国家赔偿",
             "path": "/defense/unlawful-detention-compensation", "description": "赔偿义务机关针对违法刑事拘留赔偿申请提出的答辩。", "disabled": True},
            {"id": "wrongful-conviction-compensation", "name": "刑事改判无罪国家赔偿",
             "path": "/defense/wrongful-conviction-compensation", "description": "赔偿义务机关针对刑事改判无罪赔偿申请提出的答辩。", "disabled": True},
            {"id": "failure-of-supervision-duty-compensation", "name": "怠于履行监管职责致伤致死国家赔偿",
             "path": "/defense/failure-of-supervision-duty-compensation", "description": "赔偿义务机关针对怠于履行监管职责赔偿申请提出的答辩。", "disabled": True}
        ]
    },
    "application": {
        "civil": [
            {"id": "asset-preservation", "name": "财产保全申请", "path": "/application/asset-preservation",
             "description": "在诉讼前或诉讼中申请查封、冻结对方财产。", "disabled": True},
            {"id": "wrongful-enforcement-compensation", "name": "错误执行国家赔偿", "path": "/application/wrongful-enforcement-compensation",
             "description": "因法院的执行行为错误造成损害，向该法院申请国家赔偿。", "disabled": True},
            {"id": "compulsory-enforcement", "name": "强制执行", "path": "/application/compulsory-enforcement",
             "description": "在法律文书生效后，义务人未履行义务时，向法院申请强制执行。", "disabled": True},
            {"id": "lift-travel-restrictions", "name": "暂时解除乘坐飞机、高铁限制措施", "path": "/application/lift-travel-restrictions",
             "description": "被执行人因紧急情况等原因，申请暂时解除“限高”措施。", "disabled": True},
            {"id": "participate-in-distribution", "name": "参与分配", "path": "/application/participate-in-distribution",
             "description": "在执行程序中，其他债权人申请参与对已被查封财产的分配。", "disabled": True},
            {"id": "enforcement-guarantee", "name": "执行担保", "path": "/application/enforcement-guarantee",
             "description": "被执行人提供担保，申请暂缓执行或与申请执行人和解。", "disabled": True},
            {"id": "confirm-right-of-first-refusal", "name": "确认优先购买权", "path": "/application/confirm-right-of-first-refusal",
             "description": "案件共有人或承租人等在法院拍卖财产时，申请确认并主张优先购买权。", "disabled": True},
            {"id": "enforcement-objection", "name": "执行异议", "path": "/application/enforcement-objection",
             "description": "当事人或案外人认为法院的执行行为或执行标的侵犯其权益时，提出书面异议。", "disabled": True},
            {"id": "enforcement-reconsideration", "name": "执行复议", "path": "/application/enforcement-reconsideration",
             "description": "对法院作出的执行异议裁定不服，向上级法院申请复议。", "disabled": True},
            {"id": "enforcement-supervision", "name": "执行监督", "path": "/application/enforcement-supervision",
             "description": "向检察院申请对法院的民事执行活动进行法律监督。", "disabled": True},
            {"id": "non-enforcement-of-arbitration", "name": "不予执行仲裁裁决等", "path": "/application/non-enforcement-of-arbitration",
             "description": "申请法院不予执行仲裁裁决、经司法确认的调解协议或已公证的债权文书。", "disabled": True}
        ],
        "criminal": [
            {"id": "unlawful-detention-compensation", "name": "违法刑事拘留国家赔偿", "path": "/application/unlawful-detention-compensation",
             "description": "因被采取刑事拘留措施后，决定撤销案件、不起诉或判决无罪，向赔偿义务机关申请国家赔偿。", "disabled": True},
            {"id": "wrongful-conviction-compensation", "name": "刑事改判无罪国家赔偿", "path": "/application/wrongful-conviction-compensation",
             "description": "因原判决被改判无罪，向赔偿义务机关申请羁押赔偿等国家赔偿。", "disabled": True},
            {"id": "failure-of-supervision-duty-compensation", "name": "怠于履行监管职责致伤致死国家赔偿",
             "path": "/application/failure-of-supervision-duty-compensation", "description": "因行使侦查、检察、审判职权的机关怠于履行监管职责导致在押人员伤亡，申请国家赔偿。", "disabled": True}
        ],
        "administrative": []
    }
}
